### ISSUE TITLE
More rendered elements

### ISSUE THREAD

**Issue by stevenvachon** [localvoid/vdom-benchmark#14]
I've read that React's strength is in managing a large number of elements (~5000 from the sound of things) and at the current ~100 elements, this is situation is not compared with the other libraries.

I'm not saying that we should simply increase from 100 to 5000, but have a second test.

**Comment by localvoid** [comment]
There are 5000 nodes in each test case right now.

**Comment by stevenvachon** [comment]
Oh yeah. Thanks.
