### ISSUE TITLE
README benchmark link is broken and benchmark won't run

### ISSUE THREAD

**Issue by bryonmarks-wf** [localvoid/vdom-benchmark#16]
The Run Benchmark link at https://github.com/localvoid/vdom-benchmark doesn't work.  I see in https://github.com/localvoid/vdom-benchmark/commit/ad8b773eb824a0f162744e9a5452b02e86e765c5 that this was moved.

If I go to the [link](http://vdom-benchmark.github.io/benchmark-aggregator/?cfg=http://vdom-benchmark.github.io/vdom-benchmark/config.js) specified there the page comes up but the page never gets past "Loading Config...".

**Comment by localvoid** [comment]
Thanks.
